# fly.toml app configuration file generated for knuckleball on 2024-09-26T21:06:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knuckleball'
primary_region = 'iad'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_NAME = 'Knuckleball'
  APP_ENV = 'production'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'knuckleball'
  DB_HOST = 'ep-aged-unit-a46vs3la.us-east-1.aws.neon.tech'
  DB_PORT = '5432'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  FILESYSTEM_DISK = 's3'
  AWS_DEFAULT_REGION = 'us-east-1'
  AWS_USE_PATH_STYLE_ENDPOINT = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
